feat : inventory admin
sofdev6-02-2024/The_Microbugazos pull request #42
Opened 2024-11-22 10:57 UTC by daniel-espinoza-79

## What did I do ?

- I added the inventory section so users can enter to delete products, watch them , and also search bar and sorting are implemented

2024-11-22 13:20 UTC, aguirrekarina approved these changes

2024-11-25 13:52 UTC, JorgeHB69 requested changes

2024-11-25 13:52 UTC, JorgeHB69 commented on apps/merchant-web/src/styles/general/pagination.css
> +  color: #aaa;
Try to use the colors established on global.css

2024-11-25 13:52 UTC, JorgeHB69 commented on apps/merchant-web/src/styles/general/pagination.css
> +  color: #666;
Try to use the colors established on global.css

2024-11-25 14:40 UTC, JorgeHB69 approved these changes
Good job

2024-11-25 14:41 UTC, merged