feat: invoice notification
sofdev6-02-2024/The_Microbugazos pull request #54
Opened 2024-12-04 04:20 UTC by aguirrekarina

Implement sending an email after making a purchase. 
For this functionality, the Stripe web-hook must be activated.

Command to use:

```bash
stripe listen --forward-to localhost:5001/api/payment/Stripe/web-hook/register-web-hook-event
```

Code reviewes:
@daniel-espinoza-79 
@JeferssonCL

2024-12-04 19:00 UTC, daniel-espinoza-79 approved these changes
Good Job

2024-12-04 19:26 UTC, JeferssonCL requested changes
I think that you can include information about roduct details such as variants and attributes because we are modifying price based on it

2024-12-05 14:46 UTC, JeferssonCL requested changes

2024-12-05 14:46 UTC, JeferssonCL commented on apps/merchant-api/PaymentService/src/PaymentService.Application/QueryCommands/StripeWebHookRegister/Commands/CommandHandlers/CreateEventRegisterWebHookCommandHandler.cs
> +    private async Task<BaseResponse> GetProductVariantDetails(Guid productVariantId)
This part of code is a comunnication with another service as a client so is not correct be here soyou can move this part or segment of code to product client service.

Also I'm having this problem, do you know how can I fix it the email is not arriving to me: 
![Captura desde 2024-12-05 10-54-27](https://github.com/user-attachments/assets/c4c1f8f8-da8e-4cb6-bb6a-7493326977d7)

2024-12-05 15:16 UTC, JeferssonCL approved these changes
Good job

2024-12-05 15:16 UTC, merged